// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgh6X2_tnM0oHnRG6238X8WIApiE3aUBw',
    appId: '1:263047914665:web:42e782e0f283940bfaf5b8',
    messagingSenderId: '263047914665',
    projectId: 'note-app-turbo',
    authDomain: 'note-app-turbo.firebaseapp.com',
    storageBucket: 'note-app-turbo.firebasestorage.app',
    measurementId: 'G-JG7RCJ4W4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy4cmY-ajWi52UmyWQcpFWfFqiiZYW9oE',
    appId: '1:263047914665:android:1d05d79b38f0e369faf5b8',
    messagingSenderId: '263047914665',
    projectId: 'note-app-turbo',
    storageBucket: 'note-app-turbo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoaq2Imsenqm9vB8araliDv5_gO4Rsuac',
    appId: '1:263047914665:ios:fdd44cd13d934e3efaf5b8',
    messagingSenderId: '263047914665',
    projectId: 'note-app-turbo',
    storageBucket: 'note-app-turbo.firebasestorage.app',
    iosBundleId: 'com.example.noteAppTurbo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoaq2Imsenqm9vB8araliDv5_gO4Rsuac',
    appId: '1:263047914665:ios:fdd44cd13d934e3efaf5b8',
    messagingSenderId: '263047914665',
    projectId: 'note-app-turbo',
    storageBucket: 'note-app-turbo.firebasestorage.app',
    iosBundleId: 'com.example.noteAppTurbo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgh6X2_tnM0oHnRG6238X8WIApiE3aUBw',
    appId: '1:263047914665:web:96836a5b70f63b7cfaf5b8',
    messagingSenderId: '263047914665',
    projectId: 'note-app-turbo',
    authDomain: 'note-app-turbo.firebaseapp.com',
    storageBucket: 'note-app-turbo.firebasestorage.app',
    measurementId: 'G-76THFEJ73B',
  );
}
